# "$schema" = "https://raw.githubusercontent.com/project-gauntlet/gauntlet/refs/heads/main/docs/schema/plugin_manifest.schema.json"

[gauntlet]
name = 'Date Converter'
description = """
Convert date to different formats
"""

[[entrypoint]]
id = 'convert-date'
name = 'Convert Date'
path = 'src/convert-date.tsx'
type = 'view'
description = """
Convert date to different formats
"""
icon = "icon.png"


[permissions]
clipboard = ["write"]
